POST http://localhost:3333/ruralproducer
Content-Type: application/json

{
    "producerName": "ruralproducer1",
    "farmName": "farmname1",
    "cpfCnpj": "547.083.380-15",
    "city": "Goiânia",
    "state": "Goiás",
    "totalAreaHectaresFarm": 1000,
    "arableAreaHectares": 100,
    "vegetationAreaHectares": 80,
    "plantedCrops": ["ef73954c-d0a0-402d-a44c-e344df89b815", "0e74eea6-fc6d-420a-8d67-de21d938cfae"]
}

###

GET http://localhost:3333/ruralproducer

###

PUT http://localhost:3333/ruralproducer/4b507eb2-761a-4041-8a42-071cd30ee4fe
Content-Type: application/json

{
    "producerName": "ruralproducer2",
    "farmName": "farmname2",
    "cpfCnpj": "111.222.333-11",
    "city": "Goiânia",
    "state": "Goiás",
    "totalAreaHectaresFarm": 1100,
    "arableAreaHectares": 100,
    "vegetationAreaHectares": 80
}

###

DELETE http://localhost:3333/ruralproducer/4b507eb2-761a-4041-8a42-071cd30ee4fe