POST http://localhost:3333/ruralproducer
Content-Type: application/json

{
    "producerName": "ruralproducer1",
    "farmName": "farmname1",
    "cpfCnpj": "111.222.333-11",
    "city": "Goiânia",
    "state": "Goiás",
    "totalAreaHectaresFarm": 1000,
    "arableAreaHectares": 100,
    "vegetationAreaHectares": 80,
    "plantedCrops": [1]
}

###

GET http://localhost:3333/ruralproducer

###

PUT http://localhost:3333/ruralproducer/66315400-dc09-4ce1-b7a9-aee022112b45
Content-Type: application/json

{
    "producerName": "ruralproducer2",
    "farmName": "farmname2",
    "cpfCnpj": "111.222.333-11",
    "city": "Goiânia",
    "state": "Goiás",
    "totalAreaHectaresFarm": 1100,
    "arableAreaHectares": 100,
    "vegetationAreaHectares": 80,
    "plantedCrops": [1]
}

###

DELETE http://localhost:3333/ruralproducer/82ba9102-9701-47fa-87b9-ff2ed9adc6dd